import os
from fpdf import FPDF
from datetime import datetime

class MedicalReport(FPDF):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Load Hindi font if available
        # Path is absolute to ensure FPDF finds it
        self.font_path = os.path.join(os.getcwd(), "static", "fonts", "NotoSansDevanagari-Regular.ttf")
        if os.path.exists(self.font_path):
            self.add_font("NotoSans", "", self.font_path)
            self.has_hindi = True
        else:
            self.has_hindi = False

    def header(self):
        # Header background
        self.set_fill_color(15, 23, 42) # match UI background
        self.rect(0, 0, 210, 40, 'F')
        
        # Header title
        self.set_text_color(45, 212, 191) # match primary teal
        self.set_font('helvetica', 'B', 24)
        self.cell(0, 20, 'MedEnhance AI - Clinical Report', 0, 1, 'C')
        
        # Subtitle / Timestamp
        self.set_text_color(255, 255, 255)
        self.set_font('helvetica', '', 10)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 5, f'Generated on: {timestamp} | Clinical AI Enhancement', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-20)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.multi_cell(0, 5, 'DISCLAIMER: This report is generated by MedEnhance AI and is intended for research/educational purposes only. NOT FOR DIAGNOSTIC USE.', 0, 'C')
        self.cell(0, 5, f'Page {self.page_no()}', 0, 0, 'C')

def generate_report(orig_path, enh_path, metrics, report_text):
    """
    Generates a PDF report with bilingual clinical insights.
    """
    pdf = MedicalReport()
    pdf.add_page()
    
    # 1. Comparison Images
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Side-by-Side Comparison', 0, 1)
    pdf.ln(5)
    
    # Calculate image centering
    img_w = 90
    y_start = pdf.get_y()
    pdf.image(orig_path, x=12, y=y_start, w=img_w)
    pdf.image(enh_path, x=108, y=y_start, w=img_w)
    
    # Labels
    pdf.set_font('helvetica', '', 9)
    pdf.set_y(y_start + img_w + 3)
    pdf.set_x(12)
    pdf.cell(img_w, 5, 'Figure A: Original scan', 0, 0, 'L')
    pdf.set_x(108)
    pdf.cell(img_w, 5, 'Figure B: Enhanced scan', 0, 1, 'L')
    pdf.ln(10)

    # 2. Quality Metrics
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, 'Restoration Quality Metrics', 0, 1)
    
    pdf.set_font('helvetica', '', 12)
    pdf.cell(60, 10, f"SSIM Accuracy: {metrics.get('ssim', 'N/A')}", border=0, ln=0)
    pdf.cell(60, 10, f"PSNR Gain: {metrics.get('psnr', 'N/A')} dB", border=0, ln=1)
    pdf.ln(5)

    # Line separator
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)

    # 3. Clinical Insights (English)
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, 'AI Clinical Insight (English)', 0, 1)
    
    pdf.set_font('helvetica', '', 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, report_text.get('en', 'No English analysis available.'), border=0)
    pdf.ln(10)

    # 4. Clinical Insights (Hindi)
    if pdf.has_hindi:
        pdf.set_font('NotoSans', '', 14)
        pdf.set_text_color(15, 23, 42)
        # Use only Hindi characters for header to avoid font warnings
        pdf.cell(0, 10, 'एआई क्लिनिकल इनसाइट', 0, 1)
        
        pdf.set_font('NotoSans', '', 12)
        pdf.set_text_color(50, 50, 50)
        # Clean Hindi text of any potential artifacts
        # hindi_text = report_text.get('hi', '').replace('*', '')
        hindi_text = (
            report_text.get('hi', '')
            .replace('*', '')
            .replace('•', '-')
            .replace('—', '-')
        )
        pdf.multi_cell(0, 8, hindi_text, border=0)
    else:
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, 'Hindi Analysis (Translation unavailable)', 0, 1)
        pdf.set_font('helvetica', '', 10)
        pdf.cell(0, 10, "Devanagari font was not found. Please ensure NotoSansDevanagari is in static/fonts.", 0, 1)

    # return pdf.output()
    # pdf_output = pdf.output(dest='S')

    # if isinstance(pdf_output, str):
    #     pdf_output = pdf_output.encode('latin1')

    # return pdf_output
    pdf_output = pdf.output(dest='S')

    if isinstance(pdf_output, bytearray):
        pdf_output = bytes(pdf_output)

    elif isinstance(pdf_output, str):
        pdf_output = pdf_output.encode('latin1')

    return pdf_output